### ISSUE TITLE
Infinite recursion with @sentry/browser

### ISSUE THREAD

**Issue by cpmsmith** [mysticatea/event-target-shim#26]
In a similar issue to #12, [Sentry's browser library](https://github.com/getsentry/sentry-javascript/) patches `console.assert` with a function which [includes](https://github.com/getsentry/sentry-javascript/blob/master/packages/utils/src/object.ts#L106) accessing an `Event`'s `type`, which, combined with [the assertion](https://github.com/mysticatea/event-target-shim/blob/master/src/event.mjs#L37) in `pd`, results in infinite recursion.

It's not entirely clear whose responsibility it is to fix, so I've deferred to precedent, and fixed this in the same way #12 was fixed in #27.

**Comment by Timebutt** [comment]
I am experiencing exactly the same problem right now. Browser was crashing and it was really hard to figure out where the infinite recursion was taking place. I'm very grateful for you reporting this issue here, as you offer the link with the `console.assert` patch that `@sentry/browser` seems to have done ;)

Is there anything blocking this PR right now? I'll be installing your fix in my repository to quickly fix my issue, but we'll need this fix in `master` here to help out other people experiencing this problem.

Great work by the way!

**Comment by mysticatea** [comment]
Hi. I apologize for my lack of communication.

Recently, I rewrite this package with TypeScript and it no longer uses `console.assert()`. Please check the new version.

Thank you.

**Comment by Timebutt** [comment]
Thanks @mysticatea, just pulled this into the repo that needed this fix ;)
