### ISSUE TITLE
EventTarget breaks on IE 

### ISSUE THREAD

**Issue by xTEddie** [mysticatea/event-target-shim#30]
Browser: IE 11
Version: 11.719.18362.0
Update Versions: 11.0.180

I have a project written in TypeScript. I had a sample class which extends EventTarget it did not work. 

Has anyone experience the same issue?

**Comment by WynterDing** [comment]
Same issue.

This is a very low-level dependency，if this cause IE11 blank screen, many websites will be affected.

https://github.com/mysticatea/event-target-shim/blob/master/dist/event-target-shim.js#L91~L102

**Comment by Jaffsterz** [comment]
We have the same problem due to a dependency on event-target-shim in whatwg-fetch.
Has anyone found a solution?

**Comment by xTEddie** [comment]
You can also use [event-target-shim-es5](https://github.com/compulim/event-target-shim-es5) as alternative

**Comment by mysticatea** [comment]
Hi. I apologize for my lack of communication.

I had intended this package is used along with bundlers, and if you want to support IE11, you should configure your bundlers to transpile application.

If you don't use bundlers, use [the `umd` build](https://github.com/mysticatea/event-target-shim/blob/v5.0.1/dist/event-target-shim.umd.js) that is transpiled.

----

But some build tools don't look transpiling `node_modules`.

Therefore, since `6.0.0`, this package includes ES5 build. Use `import {} from "event-target-shim/es5"` instead.
